# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - src-tauri/target/

stages:
  - build
  - test
  - compile

build-front:       # This job runs in the build stage, which runs first.
  image: node:16
  stage: build
  script:
    - yarn install --force
    - yarn build
  artifacts:
    expire_in: 1 hour
    paths:
      - dist
      - node_modules

unit-test:   # This job runs in the test stage.
  image: node:16
  stage: test    # It only starts when the job in the build stage completes successfully.
  dependencies:
    - build-front
  script:
    - |
      node -e "process.stdout.write('TODO: add tests...');"

lint-front:   # This job also runs in the test stage.
  image: node:16
  stage: test    # It can run at the same time as unit-test-job (in parallel).
  dependencies:
    - build-front
  script:
    - yarn lint

compile-binary:
  image: rust:1-slim-buster
  stage: compile
  dependencies:
    - unit-test
    - lint-front
    - build-front
  script:
    # For whole list of needed packages for Tauri, check this link:
    # https://tauri.studio/docs/get-started/setup-linux#1-system-dependencies
    # For example, patchelf and librsvg2 are used to generate an appimage file.
    - apt-get update && apt-get upgrade -y --no-install-recommends build-essential curl wget libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev libsoup2.4 libsoup2.4-dev libwebkit2gtk-4.0 libwebkit2gtk-4.0-dev
    - ./bin/tauri build
  artifacts:
    expire_in: 1 day
    paths:
      - src-tauri/target/release/bundle/